################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies

  - package-ecosystem: "npm"
    directory: "/packages/babel-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/bootstrap-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/browserslist-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/commitlint-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/cssnano-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/cypress-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/markdownlint-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/postcss-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/prettier-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/remark-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/standard-version-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/stylelint-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/textlint-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/tools/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    
  - package-ecosystem: "npm"
    directory: "/packages/webpack-config/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    reviewers:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
