################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot.json
################################################################################
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/packages/browserslist-config/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/packages/config/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/packages/eslint-config/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
